# Generated by Django 4.1.5 on 2023-02-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='influncer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=200)),
                ('image_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=400)),
                ('website', models.CharField(max_length=200)),
                ('api_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=50)),
                ('influncer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.influncer')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
