# Generated by Django 4.1.5 on 2023-02-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10),
        ),
    ]
