# Generated by Django 4.1.5 on 2023-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_coin_api_name_alter_coin_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='influncer',
            name='real_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coin',
            name='api_name',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='coin',
            name='image_url',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RemoveField(
            model_name='coin',
            name='influncer',
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(blank=True, default='BTC', max_length=10),
        ),
        migrations.AlterField(
            model_name='coin',
            name='website',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='influncer',
            name='image_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='influncer',
            name='website',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='coin',
            name='influncer',
            field=models.ManyToManyField(blank=True, to='main_app.influncer'),
        ),
    ]
