# Generated by Django 4.1.5 on 2023-02-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_coin_image_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='influncer',
            new_name='Influencer',
        ),
        migrations.RenameField(
            model_name='coin',
            old_name='influncer',
            new_name='influencer',
        ),
    ]
