# Generated by Django 4.1.5 on 2023-02-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_coin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='bio',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
