# Generated by Django 4.1.5 on 2023-02-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_influencer_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('T', 'Twitter'), ('I', 'Instagram'), ('Y', 'YouTube'), ('S', 'Snapchat'), ('F', 'Facebook'), ('P', 'Podcast'), ('B', 'Blog'), ('W', 'Website'), ('O', 'Other')], default='T', max_length=1)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.influencer')),
            ],
        ),
    ]
